# @name login
POST http://localhost:5000/app/api/v1/auths/login/users
Content-Type: application/json

{
    "email": "thaole301000@gmail.com",
    "password" : "12345"
}

###
@authToken = {{login.response.body.token}}
###

GET http://localhost:5000/app/api/v1/images?placeId=611930190aab361378748f0b
Content-Type: application/json