### 
DELETE http://localhost:5000/app/api/v1/recommendee/items/undefined
Content-Type: application/json


###
DELETE http://localhost:5000/app/api/v1/recommendee/user/topRating
Content-Type: application/json


###
DELETE http://localhost:5000/app/api/v1/recommendee/reset
Content-Type: application/json

###
POST http://localhost:5000/app/api/v1/recommendee/description
Content-Type: application/json

###
PUT  http://localhost:5000/app/api/v1/places/recombee
Content-Type: application/json


### GET
GET http://localhost:5000/app/api/v1/recommendee/getUserToUser/



###
GET http://localhost:5000/app/api/v1/recommendee/searchFuzzy/lng


###
GET